wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709901346.805897
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 100
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 100
      3:
      - 13
      - 19
      - 23
      4: 3.12.2
      5: 0.16.3
      6: 4.38.1
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 2.0e-05
batch_size:
  desc: null
  value: 30
epochs:
  desc: null
  value: 1000
